-- AlterTable
ALTER TABLE "OMA" ADD COLUMN     "createdById" TEXT;

-- AddForeignKey
ALTER TABLE "OMA" ADD CONSTRAINT "OMA_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
